package com.bosssoft.hr.javase.springexample.dao;

import com.bosssoft.hr.javase.springexample.pojo.entity.User;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import java.util.List;

@Mapper
public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table baisc_user
     *
     * @mbg.generated Wed Jun 22 18:37:48 CST 2022
     */
//    @Select("select * from baisc_user")
//    List<User> queryUser();

    int deleteByPrimaryKey(Long id);

    int insert(User record);

    User selectByPrimaryKey(Long id);

    List<User> selectAll();

    int updateByPrimaryKey(User record);

    int delete(Long id);

    int update(User user);
}