package com.bosssoft.hr.javase.springexample.pojo.vo;/*
 *
 * @author DELL
 * @date 2022/06/221854
 **/

import com.bosssoft.hr.javase.springexample.pojo.entity.User;
import com.sun.istack.internal.NotNull;
import org.springframework.beans.BeanUtils;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

public class UserVO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baisc_user.id
     *
     * @mbg.generated Wed Jun 22 18:37:48 CST 2022
     */
    private Long id;
    private String code;
    private String name;
    private String password;
    private Date birthdayDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baisc_user.id
     *
     * @return the value of baisc_user.id
     *
     * @mbg.generated Wed Jun 22 18:37:48 CST 2022
     */
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    public Date getBirthdayDate() {
        return birthdayDate;
    }

    public void setBirthdayDate(Date birthdayDate) {
        this.birthdayDate = birthdayDate;
    }
}
